### ISSUE TITLE
Create Blazor Project

### ISSUE THREAD

**Issue by thopdev** [thopdev/THopFood#1]
Create a Blazor WASM project with PWA

**Comment by tesar-tech** [comment]
What about the backend? Is it gonna be asp.net core hosted?

**Comment by thopdev** [comment]
@tesar-tech Yes, https://github.com/thopdev/THopFood/blob/main/README.md architure. For the first stream i don't wanne do only setup so start with blazor and maybe add some bunit on it. Then we can fake the services and add it on a later stream

**Comment by thopdev** [comment]
https://github.com/thopdev/THopFood/issues/11 @tesar-tech
